name: CI & CD

on:
  # Trigger the workflow on pushes to the main branch, including PR merges:
  push:
    branches:
      - main
      - feature/build-and-push

jobs:
  build-and-push-to-docker-hub:
    name: Build and Push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3.3.0
      
      - name: Docker Metadata action
        id: docker-image-metadata
        uses: docker/metadata-action@v4.4.0
        with:
          # list of Docker images to use as base name for tags
          images: |
            vovimayhem/ohmyzsh
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=sha,prefix=,format=short

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2.5.0
      
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: vovimayhem
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push release image
        id: build-release-image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          target: release
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: ${{ steps.docker-image-metadata.outputs.tags }}
          labels: ${{ steps.docker-image-metadata.outputs.labels }}

      - name: Update Description on Docker Hub
        uses: peter-evans/dockerhub-description@v3.4.1
        with:
          username: vovimayhem
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: vovimayhem/ohmyzsh
          readme-filepath: ./README.md
          short-description: ${{ github.event.repository.description }}
